# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio          = [ 1, 4, 3 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
linemode       = "size"
show_hidden    = true
show_symlink   = true

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_filter    = "nearest"
image_quality   = 50
sixel_fraction  = 15
ueberzug_scale  = 0.5
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
	{ run = 'hx "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open", for = "linux" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here (ya)", for = "unix" },
	# { run = '7z x "$1"', desc = "Extract here (7z)", for = "unix" },
]
rar-extract = [
	{ run = 'unrar x "$1"', desc = "Extract here (unrar)", for = "unix" },
]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
]
evince-open = [
	{ run = 'evince "$@"', orphan = true },
]
imv-open = [
	{ run = 'imv -n "$@" ./ -u linear', orphan = true },
]

[open]
rules = [
	{ mime = "text/*",  use = [ "edit" ] },
	{ mime = "video/*", use = [ "play" ] },
	{ mime = "audio/*", use = [ "play" ] },

	# 目录
	{ mime = "inode/directory", use = [ "edit" ] },
	# 空文件
	{ mime = "inode/empty", use = [ "edit" ] },

	{ mime = "application/json", use = [ "edit" ] },
	{ mime = "*/javascript",     use = [ "edit" ] },

	{ mime = "application/zip", use = [ "extract"  ] },
  { mime = "application/gzip", use = [ "extract"  ] },
  { mime = "application/7z-compressed", use = [ "extract"  ] },
  { mime = "application/tar", use = [ "extract"  ] },
  { mime = "application/xz", use = [ "extract"  ] },
  { mime = "application/zstd", use = [ "extract"  ] },
  { mime = "application/rar", use = [ "rar-extract"  ] },

	# Evince view
	{ mime = "application/x-cb7",              use = [ "evince-open"  ] },
	{ mime = "application/x-cbr",              use = [ "evince-open"  ] },
	{ mime = "application/x-cbt",              use = [ "evince-open"  ] },
	{ mime = "application/x-cbz",              use = [ "evince-open"  ] },
	{ mime = "image/vnd.djvu",                 use = [ "evince-open"  ] },
	{ mime = "application/x-dvi",              use = [ "evince-open"  ] },
	{ mime = "application/oxps",               use = [ "evince-open"  ] },
	{ mime = "application/vnd.ms-xpsdocument", use = [ "evince-open"  ] },
	{ mime = "application/pdf",                use = [ "evince-open"  ] },
	{ mime = "application/postscript",         use = [ "evince-open"  ] },

	# imv view
	{ mime = "image/tiff",                     use = [ "imv-open"  ] },
	{ mime = "image/x-tiff",                   use = [ "imv-open"  ] },
	{ mime = "image/png",                      use = [ "imv-open"  ] },
	{ mime = "image/jpeg",                     use = [ "imv-open"  ] },
	{ mime = "image/svg+xml",                  use = [ "imv-open"  ] },
	{ mime = "image/heif",                     use = [ "imv-open"  ] },
	{ mime = "image/heif-sequence",            use = [ "imv-open"  ] },
	{ mime = "image/heic",                     use = [ "imv-open"  ] },
	{ mime = "image/heic-sequence",            use = [ "imv-open"  ] },
	{ mime = "image/jxl",                      use = [ "imv-open"  ] },

	{ mime = "*", use = [ "open" ] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = false

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
