theme = "catppuccin_macchiato"

[editor]
# 行号显示: absolute 简单地显示每行的行号，而 relative 显示当前行的距离。当失去焦点或处于插入模式时， relative 仍将显示绝对行号
line-number = "relative"
cursorline = true
cursorcolumn = true
bufferline = "multiple"
# 用于控制弹出窗口（如自动完成、提示等）周围是否显示边框
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
# 用于在状态栏中分隔元素的字符
separator = "│"
mode.normal = "普通模式"
mode.insert = "插入模式"
mode.select = "选择模式"

[editor.lsp]
# 在状态行显示 LSP 进度消息
display-messages = true
# 显示嵌入提示
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
# 启用忽略隐藏文件
hidden = false

# 使用可见字符渲染空格的选项
[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
tab = "→"
newline = ""
tabpad = "·" # Tabs will look like "→···" (depending on tab width)
# 使用软换行
[editor.soft-wrap]
enable = true
# 软折行时，行尾可以留下的最大空闲空间
max-wrap = 25
# 在软折行时，可以保留的最大缩进量
max-indent-retain = 40
# 在软换行的行之前插入的文本
wrap-indicator = "↪"
