name: Update and Build Nix Flake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  update-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v20
      
      # Update flake
      - name: Update Nix Flake
        id: update_flake
        run: |
          set -Eeu
          nix flake update
          
      # Check if flake.lock changed
      - name: Check if flake.lock Changed
        id: check_flake_lock
        run: |
          if git diff --quiet HEAD flake.lock; then
            echo "flake_lock_changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "flake_lock_changed=true" >> "$GITHUB_OUTPUT"
          fi
          
      # Output result if no changes
      - name: Output Result
        if: steps.check_flake_lock.outputs.flake_lock_changed == 'false'
        run: echo "flake.lock not changed"
        
      # Build flake if there are changes
      - name: Build Nix Flake
        if: steps.check_flake_lock.outputs.flake_lock_changed == 'true'
        id: build_flake
        run: |
          set -Eeu
          nix build .#nixosConfigurations.nixos.config.system.build.toplevel
        continue-on-error: true
        
      # Upload flake.lock if build succeeded
      - name: Upload flake.lock if Build Succeeded
        if: |
          steps.check_flake_lock.outputs.flake_lock_changed == 'true' &&
          steps.build_flake.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: flake-lock
          path: flake.lock
          
      # Output message if build failed
      - name: Build Failed
        if: |
          steps.check_flake_lock.outputs.flake_lock_changed == 'true' &&
          steps.build_flake.outcome == 'failure'
        run: echo "Build failed, not uploading flake.lock"
